server.port: 9000

spring:
  application:
    name: livy-examples

spring.logging.file: ${LOG_FILE:target}

livy:
  host: "${LIVY_HOST:192.168.0.4}"
  port: "${LIVY_PORT:8998}"
  app:
    location: "${LIVY_SPARK_APPS_LOCATION:/usr/livy-server-0.3.0/upload/}"